name: Scrape HLTV players

on:
  schedule:
    - cron: '5 3 * * *'   # 03:05 UTC ≈ 06:05 Europe/Bucharest
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Run scraper
        run: node index.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update HLTV players CSV [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
